

export const sample_movies: any[]=[
    {
        id:'1',
        name:"Năm Đêm Kinh Hoàng",
        description:"Nhân viên bảo vệ Mike bắt đầu làm việc tại Freddy Fazbear's Pizza. Trong đêm làm việc đầu tiên, anh nhận ra mình sẽ không dễ gì vượt qua được ca đêm ở đây. Chẳng mấy chốc, anh sẽ vén màn sự thật đã xảy ra tại Freddy's.",
        category: ["Kinh dị","Hành động"],
        stars:4.5,
        imgUrl:'assets/nam-dem-kinh-hoang.jpg',
        trailerUrl:'https://www.youtube.com/watch?v=yGeoPHN0Pss',
        release_date:"25-10-2023",
      
    },
    {
        id:'2',
        name:"Đại Chiến Người Khổng Lồ",
        description:"Chứng kiến quê hương bị tàn phá, chàng thanh niên Eren Yeager quyết tâm chiến đấu với bọn Titan khổng lồ đang đe dọa hủy diệt loài người.",
        category:["Hoạt hình", "Hành động"],
        stars:4.5,
        imgUrl:'assets/dai-chien-nguoi-khong-lo.jpg',
        trailerUrl:'https://www.youtube.com/watch?v=Lkqb9IZqyAA',
        release_date:"2013",
      },
      {
        id:'3',
        name:"Lưỡi Cưa X",
        description:"Lấy bối cảnh giữa các sự kiện của hai phần phim đầu phim, John Kramer ốm yếu và tuyệt vọng đến Mexico để thực hiện một quy trình y tế thử nghiệm và mạo hiểm với hy vọng chữa khỏi bệnh ung thư của mình bằng phép màu nhưng rồi mau chóng phát hiện ra rằng toàn bộ ca phẫu thuật là một trò lừa đảo nhằm lừa đảo những người dễ bị tổn thương nhất.",
        category: ["Kinh dị"],
        stars:4.0,
        imgUrl:'assets/luoi-cua-x.jpg',
        trailerUrl:'https://www.youtube.com/watch?v=t3PzUo4P21c',
        release_date:"29-9-2023",
      },
      {
        id:'4',
        name:"Quỷ Ám: Tín Đồ (2023)",
        description:"Phần tiếp theo của bộ phim năm 1973 kể về một cô bé 12 tuổi bị một thực thể ma quỷ bí ẩn chiếm hữu, buộc mẹ cô phải tìm đến sự giúp đỡ của hai linh mục để cứu cô.",
        category: ["Kinh dị"],
        stars:3.5,
        imgUrl:'assets/quy-am.jpg',
        trailerUrl:'https://www.youtube.com/watch?v=_JHmfnvCUSk',
        release_date:"13-10-2023",
      },
      {
        id:'5',
        name:"Ác Quỷ Ma Sơ II (2023)",
        description:"Năm 1956 tại Pháp, một linh mục bị sát hại dã man, và sơ Irene đến để bắt đầu điều tra. Cô một lần nữa phải đối mặt với một ác quỷ mạnh mẽ.",
        category: ["Kinh dị"],
        stars:4.5,
        imgUrl:'assets/the-nun.jpg',
        trailerUrl:'https://www.youtube.com/watch?v=QF-oyCwaArU',
        release_date:"08-09-2023",
      },
      {
        id:'6',
        name:"Paw Patrol: Phim Siêu Đẳng (2023)",
        description:"Một mảnh thiên thạch kỳ diệu đã rơi xuống Thành Phố Phiêu Lưu, mang đến siêu năng lực cho những chú cún PAW Patrol và biến chúng thành Những Chú Cún Quyền Năng.",
        category:["Hoạt Hình","Hài hước"],
        stars:3.9,
        imgUrl:'assets/phime-sieu-dang.jpg',
        trailerUrl:'https://www.youtube.com/watch?v=yGeoPHN0Pss',
        release_date:"2023-10-25",
      },
      {
        id:'7',
        name:"Coco: Hội Ngộ Diệu kỳ (2017)",
        description:"Coco sẽ kể về hành trình của Miguel, một cậu bé say mê những giai điệu nhưng lại sinh trưởng trong một gia đình cấm đoán sự xuất hiện của âm nhạc. Miguel luôn nung nấu giấc mơ trở thành một nhạc sĩ nổi tiếng giống như thần tượng Ernesto de la Cruz. Tuy nhiên, truyền thống ngang trái của gia đình đã khiến cậu không thể chứng minh tài năng của mình. Rũ bỏ thực tế phũ phàng, Miguel tìm thấy chính mình ở Vùng Đất Linh Hồn (Land of the Dead) tuyệt đẹp và đầy sắc màu sau một chuỗi sự kiện huyền bí. Trong hành trình khám phá vùng đất mới, Miguel gặp gỡ “chuyên gia xảo quyệt” Hector. Cả hai cùng tạo nên chuyến phiêu lưu kỳ diệu để lật mở những bí mật chưa được tiết lộ về lịch sử của gia đình Miguel.",
        category: ["Hoạt hình","Hài hước"],
        stars:4.5,
        imgUrl:'assets/coco-hoi-ngo-dieu-ky.jpg',
        trailerUrl:'https://www.youtube.com/watch?v=lCN_xasQ7YY',
        release_date:"22-11-2017",
      },
      {
        id:'8',
        name:"Mavaka: Thần thoại rừng xanh",
        description:"Bộ phim hoạt hình Ukraine chuyển thể cực cuốn từ kịch thơ The Forest Song được phát hành trên 50 quốc gia trên toàn quốc chính thức đến Việt Nam vào mùa hè này. Câu chuyện kể về Mavka - người nắm giữ linh hồn của rừng xanh phải đối mặt với sự lựa chọn bất khả thi giữa tình yêu và nghĩa vụ bảo vệ khu rừng. Khi cô vô tình gặp và phải lòng với Lukas - nhạc sĩ tài ba đến khu rừng nhằm tìm kiếm loài cây mang đến sự sống vĩnh cửu theo lời dụ dỗ của Kylina - kẻ ác đang tham vọng chiếm đoạt lấy sự bình yên của khu rừng.",
        category: ["Hoạt hình"],
        stars:4.0,
        imgUrl:'assets/than-thoai-rung-xanh.jpg',
        trailerUrl:'https://www.youtube.com/watch?v=YB_e-ABeS1I',
        release_date:"02-03-2023",
      },
      {
        id:'9',
        name:"Người Nhện: Du Hành Vũ Trụ Nhện (2023)",
        description:"Miles Morales tái xuất trong phần tiếp theo của bom tấn hoạt hình từng đoạt giải Oscar - Spider-Man: Across the Spider-Verse. Sau khi gặp lại Gwen Stacy, chàng Spider-Man thân thiện đến từ Brooklyn phải du hành qua đa vũ trụ và gặp một nhóm Người Nhện chịu trách nhiệm bảo vệ các thế giới song song. Nhưng khi nhóm siêu anh hùng xung đột về cách xử lý một mối đe dọa mới, Miles buộc phải đọ sức với các Người Nhện khác và phải xác định lại ý nghĩa của việc trở thành một người hùng để có thể cứu những người cậu yêu thương nhất.",
        category: ["Hoạt hình","Hành động"],
        stars:4.5,
        imgUrl:'assets/du-hanh-vu-tru.jpg',
        trailerUrl:'https://www.youtube.com/watch?v=HVgwRbQfpCc',
        release_date:"01-06-2023",
      },
      {
        id:'10',
        name:"Xứ sở các nguyên tố (2023)",
        description:"Xứ Sở Các Nguyên Tố từ Disney và Pixar lấy bối cảnh tại thành phố các các nguyên tố, nơi lửa, nước, đất và không khí cùng chung sống với nhau. Câu chuyện xoay quanh nhân vật Ember, một cô nàng cá tính, thông minh, mạnh mẽ và đầy sức hút. Tuy nhiên, mối quan hệ của cô với Wade - một anh chàng hài hước, luôn thuận thế đẩy dòng - khiến Ember cảm thấy ngờ vực với thế giới này.",
        category: ["Hoạt hình","Hài hước"],
        stars:4.5,
        imgUrl:'assets/xu-so-nguyen-to.jpg',
        trailerUrl:'https://www.youtube.com/watch?v=yGeoPHN0Pss',
        release_date:"16-06-2023",
      },
      {
        id:'11',
        name:"Anh em Super Mario (2023)",
        description:"The Super Mario Bros. Movie xoay quanh cuộc phiêu lưu ở thế giới Vương quốc Nấm của anh em thợ sửa ống nước Mario và Luigi. Sau khi tình cờ bước tới vùng đất lạ từ một ống nước, Luigi đã bị chia tách với Mario và rơi vào tay quái vật rùa xấu xa Bowser, hắn đang âm mưu độc chiếm thế giới. Trong lúc cố gắng tìm kiếm người anh em của mình, Mario đã chạm mặt anh bạn nấm Toad và công chúa Peach. Từ đây họ sát cánh bên nhau trên hành trình ngăn chặn thế lực hắc ám.",
        category: ["Hoạt hình","Hài hước"],
        stars:4.5,
        imgUrl:'assets/super-mario.jpg',
        trailerUrl:'https://www.youtube.com/watch?v=QcinmCfoh8E',
        release_date:"25-10-2023",
      
    },
    {
        id:'12',
        name:"Fast & Furious X (2023)",
        description:"Dom Toretto và gia đình anh ta là mục tiêu của đứa con trai đầy thù hận của trùm ma túy Hernan Reyes.",
        category:["Hành động"],
        stars:4.5,
        imgUrl:'assets/fasr-furious-x.jpg',
        trailerUrl:'https://www.youtube.com/watch?v=32RAq6JzY-w',
        release_date:"19-05-2023",
      },
      {
        id:'13',
        name:"Tay Đua Cự Phách (2023)",
        description:"Câu chuyện hoàn thành ước mơ cuối cùng của một người chơi Gran Turismo tuổi teen có kỹ năng chơi game đã giúp anh giành được một loạt cuộc thi Nissan để trở thành một tay đua xe chuyên nghiệp thực sự.",
        category: ["Hành động"],
        stars:4.0,
        imgUrl:'assets/tay-dua-cu-phach.jpg',
        trailerUrl:'https://www.youtube.com/watch?v=t3PzUo4P21c',
        release_date:"11-08-2023",
      },
      {
        id:'14',
        name:"Thiện Ác Đối Đầu 3 (2023)",
        description:"Robert McCall chuyển đến sinh sống tại miền Nam nước Ý nhưng phát hiện ra bạn bè của mình bị một tổ chức mafia ở địa phương kiểm soát. Khi tính mạng của họ bị đe dọa, ông buộc phải quay trở lại con đường sát thủ để bảo vệ bạn bè.",
        category: ["Hành động"],
        stars:3.5,
        imgUrl:'assets/thien-ac-doi-dau.jpg',
        trailerUrl:'https://www.youtube.com/watch?v=VEgaQviZZPM',
        release_date:"01-09-2023",
      },
      {
        id:'15',
        name:"Những chú chó bụi đời (2023)",
        description:"[Khi Reggie bị người chủ Doug hạ đẳng của mình bỏ rơi trên những con phố tồi tàn trên đường phố, Reggie chắc chắn rằng người chủ yêu quý của mình sẽ không bao giờ cố ý rời bỏ cậu. Nhưng khi Reggie phải lòng Bug, một kẻ lang thang nói nhanh, mồm mép, yêu tự do và tin rằng chủ nhân là những kẻ ngu ngốc, Reggie cuối cùng cũng nhận ra mình đang có một mối quan hệ độc hại và bắt đầu coi Doug là kẻ nhếch nhác nhẫn tâm. ",
        category: ["Hài hước"],
        stars:4.0,
        imgUrl:'assets/nhung-chu-cho-bui-doi.jpg',
        trailerUrl:'https://www.youtube.com/watch?v=26Xq6_g2r6Q',
        release_date:"18-08-2023",
      },
      {
        id:'16',
        name:"Ninja Rùa: Hỗ loạn tuổi dậy thì (2023)",
        description:"Sau nhiều năm được che chở khỏi thế giới loài người, anh em nhà Rùa lên đường chiếm được cảm tình của người dân New York và được chấp nhận như những thanh thiếu niên bình thường thông qua những hành động anh hùng. Người bạn mới April O'Neil giúp họ đương đầu với một tổ chức tội phạm bí ẩn, nhưng họ sớm gặp rắc rối khi một đội quân dị nhân tấn công họ.",
        category:["Hoạt Hình","Hài hước"],
        stars:4.3,
        imgUrl:'assets/ninja-rua.jpg',
        trailerUrl:'https://www.youtube.com/watch?v=IHvzw4Ibuho',
        release_date:"02-08-2023",
      },
      {
        id:'17',
        name:"Ruby Thủy Quán Tuổi Teen (2023)",
        description:"Ruby Thủy Quái Tuổi Teen kể về cô bé Ruby Gillman nhút nhát, tình cờ phát hiện ra mình là một phần của dòng dõi thủy quái hoàng gia huyền thoại. Và kể từ giây phút này, số phận của cô bé dưới đáy đại dương bỗng thay thổi hoàn toàn, cùng với đó là một sứ mệnh lớn hơn tất cả những gì cô từng mơ đến.",
        category: ["Hoạt hình","Hài hước"],
        stars:4.5,
        imgUrl:'assets/thuy-quai-tuoi-teen.jpg',
        trailerUrl:'https://www.youtube.com/watch?v=6sJcL5sm9n4',
        release_date:"02-09-2022",
      },
      {
        id:'18',
        name:"Người Nhện Không Có Nhà (2021)",
        description:"Peter Parker đã bị lộ mặt và không còn có thể tách biệt cuộc sống bình thường của mình với những yêu cầu cao của việc trở thành một Siêu anh hùng. Khi anh ta yêu cầu sự giúp đỡ từ Doctor Strange, mọi thứ càng trở nên nguy hiểm hơn, buộc anh ta phải khám phá ra ý nghĩa thực sự của việc trở thành Người Nhện.",
        category: ["Khoa học viễn tưởng","Hành động"],
        stars:4.0,
        imgUrl:'assets/nguoi-nhen-ko-co-nha.jpg',
        trailerUrl:'https://www.youtube.com/watch?v=OB3g37GTALc',
        release_date:"02-03-2023",
      },
      {
        id:'19',
        name:"Cuộc Chiến Vô Cực (2018)",
        description:"Sau chuyến hành trình độc nhất vô nhị không ngừng mở rộng và phát triển vụ trũ điện ảnh Marvel, bộ phim Avengers: Cuộc Chiến Vô Cực sẽ mang đến màn ảnh trận chiến cuối cùng khốc liệt nhất mọi thời đại. Biệt đội Avengers và các đồng minh siêu anh hùng của họ phải chấp nhận hy sinh tất cả để có thể chống lại kẻ thù hùng mạnh Thanos trước tham vọng hủy diệt toàn bộ vũ trụ của hắn.",
        category: ["Khoa học viễn tưởng","Hành động"],
        stars:4.5,
        imgUrl:'assets/cuoc-chien-co-cuc.jpg',
        trailerUrl:'https://www.youtube.com/watch?v=k2b2Jb24hQc',
        release_date:"25-04-2023",
      },
      {
        id:'20',
        name:"Avatar: Dòng chảy của nước",
        description:"Câu chuyện của “Avatar: Dòng Chảy Của Nước” lấy bối cảnh 10 năm sau những sự kiện xảy ra ở phần đầu tiên. Phim kể câu chuyện về gia đình mới của Jake Sully (Sam Worthington thủ vai) cùng những rắc rối theo sau và bi kịch họ phải chịu đựng khi phe loài người xâm lược hành tinh Pandora.",
        category: ["Khoa học viễn tưởng","Hành động"],
        stars:4.5,
        imgUrl:'assets/avatar.jpg',
        trailerUrl:'https://www.youtube.com/watch?v=gq2xKJXYZ80',
        release_date:"16-12-2023",
      }

]
export const sample_categories:any[] = [
  { name: 'All', count:  10},
  { name: 'Kinh dị', count: 10 },
  { name: 'Hành động', count: 10 },
  { name: 'Hoạt hình', count: 10 },
  { name: 'Khoa học viễn tưởng', count: 10 },
  { name: 'Hài hước', count: 10 },


]
export const sample_users: any[] = [
  {
      name: "Phạm Văn Hiếu",
      email:"phvanhieu@gmail.com",
      password:"123123",
      address: "VN",
      isAdmin: true
  },

  {
      name: 'Will',
      email:"will@gmail.com",
      password:"123123",
      address: "Fr",
      isAdmin: false
  },
];